import { Inter, Marcellus_SC } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import "../../lib/fontawesome";

const interMono = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: "400",
});

const marcellusFont = Marcellus_SC({
  variable: "--font-marcellus-sc",
  subsets: ["latin"],
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="en">
      <body className={`${interMono.variable} ${marcellusFont.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
