import { Bungee_Tint } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import HomePage from "./HomePage/Page";

const bungeeMono = Bungee_Tint({
  variable: "--font-bungee",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="en">
      <body className={`${bungeeMono.variable}`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
